#!/bin/bash
# 数据库导入导出脚本
BACKUP_FILE=/tmp/dump.sql
HOST=''
if [ $1 ]; then
    echo $1
    HOST=$1
else
    read -p "请输入拷贝数据库的地址: " HOST
fi
read -p "请输入密码（无密码回车忽略）: " -s PASSWORD

if [ -z $HOST ]; then
    echo -e "\n没有输入数据库地址，已退出"
    exit 1
fi

function main() {
    echo "开始备份数据库..."
    exportDB
    echo "备份数据库完成"
    importDB
    echo "导入数据库完成"
}

function exportDB() {
    mysql -uroot -h ${HOST} -e "show databases" -p${PASSWORD} |
        grep "keepwork-rls" |
        xargs -I '{}' mysqldump --column-statistics=0 -uroot -h ${HOST} --databases '{}' -p${PASSWORD} \
            --default-character-set=utf8 --max_allowed_packet=48M \
            --set-gtid-purged=OFF \
            >$BACKUP_FILE
}

function importDB() {
    echo "开始导入数据库..."
    mysql -uroot -e "SET GLOBAL innodb_flush_log_at_trx_commit=0;
SET GLOBAL sync_binlog=0;
SET sql_log_bin=off;
source /tmp/dump.sql;
SET GLOBAL innodb_flush_log_at_trx_commit=1;
SET GLOBAL sync_binlog=1;"
    echo "导入数据库完成"
}

# mysqldump参数
# --set-gtid-purged=OFF: 记录binlog日志,如果不加,不记录binlog日志（用了gtid的情况）
# --ignore-table=databaseName.tableName: 忽略的表

main
